// Fonts
import "../../assets/Inter-Regular.ttf";
import "../../assets/Inter-Bold.ttf";

// Images
import "../../assets/mascots-large.png";
import "../../assets/map.png";
import "../../assets/map-info.png";
import "../../assets/about.png";
import "../../assets/about-info.png";
import "../../assets/contact.png";
import "../../assets/contact-info.png";
import "../../assets/guides.png";
import "../../assets/guides-info.png";
import "../../assets/marker.png";
import "../../assets/marker-1.png";
import "../../assets/marker-2.png";
import "../../assets/marker-3.png";
import "../../assets/map-border.png";
